version: "3.2"
services:
  mongo:
    image: mongo
    volumes:
      - /Users/vyacheslavbiryukov/data/mongodb/db:/data/db
    ports:
      - "27017:27017"
    command: mongod
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  server:
    image: node
    build:
        context: .
    container_name: server_app
    user: "node"
    environment:
        - NODE_ENV=production
    volumes:
        - .:/home/app
    ports:
        - "8000:3000"
    links: 
        - mongo
    working_dir: /home/app
    command: npm run start:server